post:
  x-eov-operation-id: retryExecution
  x-eov-operation-handler: v1/handlers/executions/executions.handler
  tags:
    - Execution
  summary: Retry an execution
  description: Retry an execution from your instance.
  parameters:
    - $ref: '../schemas/parameters/executionId.yml'
    - $ref: '../schemas/parameters/loadWorkflow.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/execution.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
    '409':
      $ref: '../../../../shared/spec/responses/conflict.yml'
